# Generated by Django 5.2.14 on 2026-06-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('accounts', '0002_doctor_pharmacist_approval'),
    ]

    operations = [
    ]
