# Generated by Django 5.2.14 on 2026-06-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
