# Generated by Django 5.2.14 on 2026-06-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('dispensed', 'Dispensed')], default='draft', max_length=20),
        ),
        migrations.DeleteModel(
            name='PrescriptionItem',
        ),
    ]
